# Generated by Django 4.1.3 on 2022-11-27 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_exercise_status_alter_exercise_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='type',
        ),
        migrations.CreateModel(
            name='ExerciseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_types', to='webapp.exercise', verbose_name='Задача')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_exercises', to='webapp.type', verbose_name='Тип')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='types',
            field=models.ManyToManyField(blank=True, related_name='exercises', through='webapp.ExerciseType', to='webapp.type'),
        ),
    ]
