# Generated by Django 4.1.3 on 2022-11-27 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_remove_exercise_type_exercisetype_exercise_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='types',
            new_name='types_old',
        ),
    ]
