# Generated by Django 4.1.3 on 2022-11-27 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_rename_types_exercise_types_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='types_old',
            field=models.ManyToManyField(blank=True, related_name='exercises_set', through='webapp.ExerciseType', to='webapp.type'),
        ),
    ]
