# Generated by Django 4.1.3 on 2022-11-27 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_alter_exercise_types_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='types',
            field=models.ManyToManyField(blank=True, related_name='exercises', to='webapp.type'),
        ),
    ]
