# Generated by Django 4.1.3 on 2022-11-27 20:24

from django.db import migrations

def transfer_types(apps, schema_editor):
    Exercise = apps.get_model('webapp.Exercise')
    for exercise in Exercise.objects.all():
        exercise.types.set(exercise.types_old.all())


def rollback_transfer(apps, schema_editor):
    Exercise = apps.get_model('webapp.Exercise')
    for exercise in Exercise.objects.all():
        exercise.types_old.set(exercise.types.all())


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_exercise_types'),
    ]

    operations = [
        migrations.RunPython(transfer_types,
                             rollback_transfer)
    ]
