# Generated by Django 4.1.3 on 2022-11-27 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20221127_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='types_old',
        ),
        migrations.DeleteModel(
            name='ExerciseType',
        ),
    ]
