# Generated by Django 4.1.3 on 2022-12-06 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_project_alter_exercise_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='exercises', to='webapp.project', verbose_name='Проект'),
            preserve_default=False,
        ),
    ]
