# Generated by Django 4.1.3 on 2023-01-09 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_alter_project_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('add_user_in_project', 'Добавить пользователя в проект')]},
        ),
    ]
